---
language: node_js
node_js:
  - 11.10.0

dist: trusty

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@6.8.0
  - npm install

script:
  - make lint

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
