name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: make dependencies
      - run: make lint
      - run: make build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
