name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make dependencies
      - run: make lint
      - run: make build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
